server:
  port: 8010

spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    protocol: smtp
    username: apikey
    password: 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
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true